dbt_transform:
  outputs:
    dev:
      dbname: "{{ env_var('POSTGRES_DBNAME')}}"
      host: "{{ env_var('POSTGRES_HOST')}}"
      pass: "{{ env_var('POSTGRES_PASSWORD')}}"
      schema: "{{ env_var('POSTGRES_SCHEMA')}}"
      port: 5432
      threads: 1
      type: postgres
      user: "{{ env_var('POSTGRES_USER')}}"
  target: dev
